# Generated by Django 5.0.1 on 2024-01-19 07:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("esgrow_backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default="null@python.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="hello", max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ComplianceDocuments",
            fields=[
                (
                    "compliance_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="")),
                (
                    "party_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="esgrow_backend.user",
                    ),
                ),
                (
                    "party_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="esgrow_backend.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EscrowTransactions",
            fields=[
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=100, max_digits=1000)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("Initiated", "Initiated"),
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=200,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="esgrow_backend.user",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="esgrow_backend.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonetaryTransactions",
            fields=[
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("external_entity", models.CharField(max_length=200)),
                ("external_reference", models.CharField(max_length=200, null=True)),
                ("amount", models.DecimalField(decimal_places=100, max_digits=1000)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("Initiated", "Initiated"),
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=200,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="esgrow_backend.user",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Transactions",
        ),
    ]
