# Generated by Django 5.0.1 on 2024-01-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("esgrow_backend", "0003_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escrowtransactions",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name="monetarytransactions",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
