# Generated by Django 5.0.1 on 2024-01-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("esgrow_backend", "0006_user_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowtransactions",
            name="from_user_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="escrowtransactions",
            name="from_user_confirmed_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="escrowtransactions",
            name="time_updated_on_users",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="escrowtransactions",
            name="to_user_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="escrowtransactions",
            name="to_user_confirmed_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="escrowtransactions",
            name="updated_on_users",
            field=models.BooleanField(default=False),
        ),
    ]
