# Generated by Django 5.0.1 on 2024-01-23 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("esgrow_backend", "0010_disputes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="disputes",
            old_name="transaction_id",
            new_name="transaction",
        ),
    ]
