# Generated by Django 5.0.1 on 2024-01-23 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("esgrow_backend", "0011_rename_transaction_id_disputes_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="disputes",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="disputes",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
